repo: "hero-banner"
canvasCourse: "web-dev-1"

inherit:
  - naming-restrict-live
  - git-2
  - html
  - css
  - box-sizing
  - body-margin-0
  - img-flex
  - google-fonts

html:
  - path: "index.html"
    outline: false
    has:
      - ['link[href*="Open+Sans"]', 'The Google Font, `Open Sans` (regular, italic & bold) is missing']
      - "div"
      - "div img.img-flex"
      - "div h2"
      - "div p"
    search:
      - "Giant space moths invade Earth"
      - "Our friendly giant, nuclear radiated lizard steps up to battle against the nefarious space moths"
      - "placeholder-16by9\\.svg"

css:
  - path: "css/main.css"
    has:
      - ['.banner']
    search:
      - "Open Sans"
      - "position: relative"
      - "position: absolute"
      - "left:"
      - "bottom:"
      - "translate"
      - "rgba\\("
      - "max-height"
      - "overflow: hidden"

screenshots:
  - path: "index.html"
    sizes:
      650: 10
      1400: 9
